[build]
  command = "ng build"
  publish = "dist/jasonhollidaymagic"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
